Remove inital extra spacing by parskip
SoftVarE-Group/SlideTemplate pull request #59
Opened 2023-05-26 10:09 UTC by EagleoutIce

Fixes #58.

The solution is rather simple (tested with texlive23 and some older versions), we remove
the additionally introduced `\parskip` before `upper` begins. The reason for this seems indeed to be the new color mechanism in tcolorbox which introduces a parskip (normally, this would be set to `\z@`/`0pt` but Benno's modification resets it with the next marginparestore.

2023-05-26 10:51 UTC, ekuiter commented
Thanks for the quick fix! The good thing is, the margin is now gone for normal text.
Unfortunately, the bullet points are now eager to also move up.

![grafik](https://github.com/SoftVarE-Group/SlideTemplate/assets/4258713/035aa206-ab1e-4997-85c5-eeae50c7c0f2)

Example:

```tex
\documentclass[aspectratio=169, 8pt]{beamer}
\usepackage{../SoftVarE-SlideTemplate/beamerthemeuulm}
\begin{document}
\begin{frame}
	\mynote{hooray}{it works}

	\mynote{oh no}{
		\begin{itemize}
			\item or does it?
		\end{itemize}
	}
\end{frame}
\end{document}
```

2023-05-26 10:54 UTC, ekuiter requested changes
The fix removes margin above text, but not above enumerate/itemize.

2023-05-26 19:04 UTC, EagleoutIce commented
Thank you for noticing @ekuiter. An additional investigation showed, that the parskip will be restored, so setting it to `\z@` before entering the upper box part seems to automatically fix all problems. Does this work for you too?

2023-05-26 20:12 UTC, ekuiter commented
> automatically fix all problems

I don't hear that often :D
Regarding your fix - I'll check it again after the holiday.

2023-05-28 05:53 UTC, Benno2000 approved these changes
@EagleoutIce I just checked your fix and now everything seems to work fine!

2023-05-30 04:42 UTC, tthuem commented
@Benno2000 Could you please check whether intended skips between paragraphs do also work as expected? Also, have you tried nested colorboxes?

Maybe we should create some test slides that cover corner cases and which we could visually compare with each other in every pull request or at least before every release. Could you start such slides (e.g., in a file called tests.tex/pdf)?

2023-05-30 07:04 UTC, ekuiter approved these changes
I tried the fix on our product-line lecture, and it now seems to work as intended.

2023-06-15 15:51 UTC, merged