feat: add demo slides for using beamer lectures
SoftVarE-Group/SlideTemplate pull request #62
Opened 2023-07-04 21:17 UTC by Benno2000

I created some demo slides to illustrate how to use beamer lectures with the template.

2023-07-14 10:28 UTC, tthuem commented
I guess we need at least three lecture parts to illustrate how it works (e.g., with includeonlylecture). Also, maketitle should be used for every lecture, ideally also with a different lecture title (e.g., subtitle).

2023-08-28 05:46 UTC, tthuem requested changes
We are on a good way, but still some parts are missing.

2023-08-28 05:46 UTC, tthuem commented on lecture-demo/lectureDemo.tex
> +    %%% Lecture 1 %%%
overview on lectures still missing

2023-08-28 05:46 UTC, tthuem commented on lecture-demo/lectureDemo.tex
> +    \begin{frame}{First Slide of Lecture \thelecture}
Second Slide?

Why not using subsections here?

2023-08-28 05:46 UTC, tthuem commented on lecture-demo/lectureDemo.tex
> +    %%% Lecture 1 %%%
also it would be good to illustrate how jumps between lectures work

2023-08-28 05:46 UTC, tthuem commented on lecture-demo/lectureDemo.tex
> +\includeonlylecture{lecture 1}
would be good to indicate also how to generate the second or all lectures (e.g., with commands in comments)

2023-08-28 05:46 UTC, tthuem commented on beamerthemeuulm.sty
> +}
I am missing subtitles at the beginning of each lecture (could indicate the topic of each lecture)

2023-08-28 05:46 UTC, tthuem commented on lecture-demo/lectureDemo.tex
> +\title{Beamer Lecture Test}
would be good to use a caption here such that it is clear whether this is the lecture series or a single 90-minute lecture

2023-09-26 11:13 UTC, Benno2000 commented
I updated the example slides for using lectures with our template:
- The `lectureDemo`-slides define a `\lectureoverviewslide` command that can once be manually adjusted to contain all lectures. It then displays the **list of all defined lectures** on the left side and automatically generates a **toc of the current lecture** on the right side.
- There are **three lectures** with **two sections** each to illustrate how lectures can be used together with sections.
- At the beginning of each lecture, a **titleslide** and a **lecture overview** is generated.
- It is illustrated how only **single lectures** can be included using `\includeonlylecture`

Regarding the template, there are a few modifications in `\AtBeginLecture`:
- At the beginning of each lecture, a new `\part` is being generated in order to **reset the sections** for the toc.
- The **section** and **frame numbers** are reset to `0`
- The **subtitle** is set to the **current lecture number** and **title**. This enables generating a new title slide for each lecture that has the overall title as title and the lecture title underneath it as subtitle.

2023-09-26 12:39 UTC, tthuem commented
@Benno2000 The links in the PDF to other lectures do not work. Is it a problem on my end? Does it work on your setup?

2023-09-26 12:41 UTC, tthuem commented
The overview slide still has a weird footer, but we can also fix that later:
![image](https://github.com/SoftVarE-Group/SlideTemplate/assets/5330357/feb85c9b-2c2c-44b1-833c-388d3f1ead1a)

2023-09-28 09:32 UTC, Benno2000 commented
@tthuem 

> The links in the PDF to other lectures do not work. Is it a problem on my end? Does it work on your setup?

When I tried it a few days ago, the links were not clickable within VS-Code but in Adobe Acrobat it worked fine. However it that does not work anymore now, too. I'll try to figure out what the issue is here.

> The overview slide still has a weird footer, but we can also fix that later

That's right, I'd suggest to fix that in a separate issue. For now, we could just use `[plain]` for the overview slides, which looks better in my opinion anyway in this case.

2023-09-28 10:50 UTC, Benno2000 commented
I fixed the lecture links by using `\hyperlink` instead of `\href`. Now they should be clickable.

2023-09-29 09:24 UTC, tthuem commented
@Benno2000  Using [plain] for the overview slides sounds good, have not thought of that yet. Go ahead with the merge then.

2023-09-30 16:21 UTC, merged